// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScholarBridge.Models;

#nullable disable

namespace ScholarBridge.Migrations
{
    [DbContext(typeof(ScholarBridgeContext))]
    [Migration("20260511210345_DonorNameAndSurname")]
    partial class DonorNameAndSurname
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScholarBridge.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ScholarshipFkId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserFkId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ScholarshipFkId");

                    b.HasIndex("UserFkId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ScholarBridge.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("DonatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("IsAnonymous")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("ScholarshipFkId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UserFkId")
                        .HasColumnType("int");

                    b.HasKey("DonationId");

                    b.HasIndex("ScholarshipFkId");

                    b.HasIndex("UserFkId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("ScholarBridge.Models.DonorDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DonorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("DonorDetails");
                });

            modelBuilder.Entity("ScholarBridge.Models.OrganizationDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OrgName")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("OrganizationDetails");
                });

            modelBuilder.Entity("ScholarBridge.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ScholarBridge.Models.Scholarship", b =>
                {
                    b.Property<int>("ScholarshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScholarshipId"));

                    b.Property<decimal?>("AmountPerStudent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<int?>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<bool?>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<int?>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("RequirementSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserFkId")
                        .HasColumnType("int");

                    b.HasKey("ScholarshipId");

                    b.HasIndex("UserFkId");

                    b.ToTable("Scholarships");
                });

            modelBuilder.Entity("ScholarBridge.Models.StudentDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DormitoryPath")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("FamilyIncome")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("GPA");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("StudentCertificatePath")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentSurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TranscriptPath")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("StudentDetails");
                });

            modelBuilder.Entity("ScholarBridge.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScholarBridge.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int?>("RoleFkId")
                        .HasColumnType("int");

                    b.Property<int?>("UserFkId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleFkId");

                    b.HasIndex("UserFkId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ScholarBridge.Models.Application", b =>
                {
                    b.HasOne("ScholarBridge.Models.Scholarship", "ScholarshipFk")
                        .WithMany("Applications")
                        .HasForeignKey("ScholarshipFkId")
                        .HasConstraintName("FK_Applications_Scholarships");

                    b.HasOne("ScholarBridge.Models.StudentDetail", "UserFk")
                        .WithMany("Applications")
                        .HasForeignKey("UserFkId")
                        .HasConstraintName("FK_Applications_StudentDetails");

                    b.Navigation("ScholarshipFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("ScholarBridge.Models.Donation", b =>
                {
                    b.HasOne("ScholarBridge.Models.Scholarship", "ScholarshipFk")
                        .WithMany("Donations")
                        .HasForeignKey("ScholarshipFkId")
                        .HasConstraintName("FK_Donations_Scholarships");

                    b.HasOne("ScholarBridge.Models.DonorDetail", "UserFk")
                        .WithMany("Donations")
                        .HasForeignKey("UserFkId")
                        .HasConstraintName("FK_Donations_DonorDetails");

                    b.Navigation("ScholarshipFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("ScholarBridge.Models.DonorDetail", b =>
                {
                    b.HasOne("ScholarBridge.Models.User", "User")
                        .WithOne("DonorDetail")
                        .HasForeignKey("ScholarBridge.Models.DonorDetail", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_DonorDetails_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarBridge.Models.OrganizationDetail", b =>
                {
                    b.HasOne("ScholarBridge.Models.User", "User")
                        .WithOne("OrganizationDetail")
                        .HasForeignKey("ScholarBridge.Models.OrganizationDetail", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationDetails_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarBridge.Models.Scholarship", b =>
                {
                    b.HasOne("ScholarBridge.Models.OrganizationDetail", "UserFk")
                        .WithMany("Scholarships")
                        .HasForeignKey("UserFkId")
                        .HasConstraintName("FK_Scholarships_OrganizationDetails");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("ScholarBridge.Models.StudentDetail", b =>
                {
                    b.HasOne("ScholarBridge.Models.User", "User")
                        .WithOne("StudentDetail")
                        .HasForeignKey("ScholarBridge.Models.StudentDetail", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentDetails_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarBridge.Models.UserRole", b =>
                {
                    b.HasOne("ScholarBridge.Models.Role", "RoleFk")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleFkId")
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("ScholarBridge.Models.User", "UserFk")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserFkId")
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("RoleFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("ScholarBridge.Models.DonorDetail", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("ScholarBridge.Models.OrganizationDetail", b =>
                {
                    b.Navigation("Scholarships");
                });

            modelBuilder.Entity("ScholarBridge.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ScholarBridge.Models.Scholarship", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("ScholarBridge.Models.StudentDetail", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("ScholarBridge.Models.User", b =>
                {
                    b.Navigation("DonorDetail");

                    b.Navigation("OrganizationDetail");

                    b.Navigation("StudentDetail");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
